"""extract_user_story_activity

Revision ID: 08baba0dd101
Revises: 
Create Date: 2026-01-13 18:44:01.485265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08baba0dd101'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_reset_user'), table_name='password_reset_tokens')
    op.drop_index(op.f('idx_reset_valid'), table_name='password_reset_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_reset_valid'), 'password_reset_tokens', ['used', 'expires_at'], unique=False)
    op.create_index(op.f('idx_reset_user'), 'password_reset_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###
